### ISSUE TITLE
bom.yaml is empty

### ISSUE THREAD

**Issue by luxe** [vmware/rules_oss_audit#4]
### Describe the bug

Please see our integration:
https://github.com/bazelbuild/bazel-buildfarm/compare/luxe/oss_audit?expand=1

We use `oss_audit` on a `pkg_rpm` rule.  This is similar to what `rules_oss_audit` shows in their `examples/`.  

we can build it:  
```
bazel build :buildfarm-server-audit

INFO: Found 1 target...
Target //:buildfarm-server-audit up-to-date:
  bazel-bin/buildfarm-server-rpm.bom.yaml
  bazel-bin/buildfarm-server-rpm.bom-issues.yaml
INFO: Elapsed time: 0.069s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

but the BOM is empty:  
```
cat bazel-bin/buildfarm-server-rpm.bom.yaml
{}
```

Maybe we packaged it incorrectly?  We also excluded `approved_list` / `denied_list` attributes (hopefully not necessary).  I will need to look more closely at the example rpm and compare it to how ours is built.  Let me know what the cause might be.

**Comment by luxe** [comment]
Upgrading `rules_jvm_external` to 4.2 did not resolve the issue.  

I also tried to build the rpm using the same pkg rules as the example.  This lead to an interesting error:  
```
ERROR: /home/luxe/.cache/bazel/_bazel_luxe/56c589a07cdcca616ecf15fab617b563/external/googleapis/BUILD.bazel:16:19: in @rules_oss_audit//oss_audit:java/oss_audit.bzl%_collect_maven_bom aspect on java_proto_library rule @googleapis//:google_devtools_build_v1_build_events_java_proto: 
Traceback (most recent call last):
	File "/home/luxe/.cache/bazel/_bazel_luxe/56c589a07cdcca616ecf15fab617b563/external/rules_oss_audit/oss_audit/java/oss_audit.bzl", line 62, column 47, in _collect_maven_bom_impl
		class_jar = _target[JavaInfo].outputs.jars[0].class_jar
Error: index out of range (index is 0, but sequence has 0 elements)
```

Makes me think the rpm was not constructed correctly because oss_audit can't find any jars inside of it?

**Comment by luxe** [comment]
https://github.com/vmware/rules_oss_audit/pull/5 resolves the issue for me.  There is a related issue around implicit deps, but it doesn't prevent me from creating BOMs.  Feel free to close. Thanks!

**Comment by danielmachlab** [comment]
> Feel free to close.
@luxe leaving this issue open to address issue around implicit deps. Thanks for your involvement in creating these issues!
